ALTER TABLE system_notice
    MODIFY COLUMN title VARCHAR(200) NOT NULL COMMENT '标题',
    MODIFY COLUMN summary VARCHAR(500) COMMENT '摘要',
    MODIFY COLUMN target_roles TEXT NOT NULL COMMENT '目标角色JSON',
    MODIFY COLUMN channels TEXT NOT NULL COMMENT '通知渠道JSON';
